import { Company, Signal } from "@/types/company";
import { computeScoreBreakdown } from "@/lib/scoring";

export const mockCompanies: Company[] = [
  {
    id: "c001",
    name: "SynthBio Labs",
    website: "https://synthbiolabs.ai",
    sector: "BioTech",
    stage: "Series A",
    country: "United States",
    city: "San Francisco",
    foundedYear: 2022,
    raisedAmount: 18500000,
    lastFundingDate: "2025-11-15",
    employeesEstimate: "51–100",
    score: 87,
    signalVelocity: 9.2,
    tags: ["AI", "Drug Discovery", "Genomics"],
    createdAt: "2025-08-01T00:00:00Z",
  },
  {
    id: "c002",
    name: "AeroFlux",
    website: "https://aeroflux.io",
    sector: "CleanTech",
    stage: "Seed",
    country: "Germany",
    city: "Berlin",
    foundedYear: 2023,
    raisedAmount: 4200000,
    lastFundingDate: "2025-09-22",
    employeesEstimate: "11–50",
    score: 74,
    signalVelocity: 7.1,
    tags: ["Energy Storage", "Sustainability"],
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "c003",
    name: "NeuraChain",
    website: "https://neurachain.xyz",
    sector: "AI / ML",
    stage: "Series B+",
    country: "United States",
    city: "New York",
    foundedYear: 2020,
    raisedAmount: 65000000,
    lastFundingDate: "2025-07-10",
    employeesEstimate: "101–250",
    score: 92,
    signalVelocity: 9.8,
    tags: ["LLM Infrastructure", "Enterprise AI"],
    createdAt: "2025-06-15T00:00:00Z",
  },
  {
    id: "c004",
    name: "PayCircle",
    website: "https://paycircle.co",
    sector: "FinTech",
    stage: "Series A",
    country: "United Kingdom",
    city: "London",
    foundedYear: 2021,
    raisedAmount: 12000000,
    lastFundingDate: "2025-10-05",
    employeesEstimate: "51–100",
    score: 79,
    signalVelocity: 6.8,
    tags: ["Payments", "Cross-border", "B2B"],
    createdAt: "2025-07-20T00:00:00Z",
  },
  {
    id: "c005",
    name: "VoxHealth",
    website: "https://voxhealth.care",
    sector: "HealthTech",
    stage: "Seed",
    country: "Canada",
    city: "Toronto",
    foundedYear: 2023,
    raisedAmount: 3800000,
    lastFundingDate: "2025-12-01",
    employeesEstimate: "11–50",
    score: 71,
    signalVelocity: 5.5,
    tags: ["Telemedicine", "NLP", "Patient Care"],
    createdAt: "2025-10-10T00:00:00Z",
  },
  {
    id: "c006",
    name: "Orbitly",
    website: "https://orbitly.space",
    sector: "SpaceTech",
    stage: "Pre-Seed",
    country: "United States",
    city: "Austin",
    foundedYear: 2024,
    raisedAmount: 1200000,
    lastFundingDate: "2025-08-18",
    employeesEstimate: "1–10",
    score: 63,
    signalVelocity: 4.2,
    tags: ["Satellite Data", "Earth Observation"],
    createdAt: "2025-11-01T00:00:00Z",
  },
  {
    id: "c007",
    name: "CodeSphere",
    website: "https://codesphere.dev",
    sector: "DevTools",
    stage: "Series A",
    country: "Germany",
    city: "Munich",
    foundedYear: 2021,
    raisedAmount: 14000000,
    lastFundingDate: "2025-06-28",
    employeesEstimate: "51–100",
    score: 82,
    signalVelocity: 8.0,
    tags: ["Developer Platform", "Cloud IDE"],
    createdAt: "2025-05-15T00:00:00Z",
  },
  {
    id: "c008",
    name: "AgriVision",
    website: "https://agrivision.farm",
    sector: "AgriTech",
    stage: "Seed",
    country: "India",
    city: "Bangalore",
    foundedYear: 2022,
    raisedAmount: 2800000,
    lastFundingDate: "2025-11-30",
    employeesEstimate: "11–50",
    score: 68,
    signalVelocity: 5.9,
    tags: ["Precision Agriculture", "Computer Vision"],
    createdAt: "2025-09-20T00:00:00Z",
  },
  {
    id: "c009",
    name: "CyberVault",
    website: "https://cybervault.sec",
    sector: "CyberSecurity",
    stage: "Series B+",
    country: "Israel",
    city: "Tel Aviv",
    foundedYear: 2019,
    raisedAmount: 45000000,
    lastFundingDate: "2025-05-12",
    employeesEstimate: "101–250",
    score: 88,
    signalVelocity: 8.7,
    tags: ["Zero Trust", "Cloud Security"],
    createdAt: "2025-04-10T00:00:00Z",
  },
  {
    id: "c010",
    name: "EduForge",
    website: "https://eduforge.learn",
    sector: "EdTech",
    stage: "Pre-Seed",
    country: "Singapore",
    city: "Singapore",
    foundedYear: 2024,
    raisedAmount: 800000,
    lastFundingDate: "2025-10-20",
    employeesEstimate: "1–10",
    score: 55,
    signalVelocity: 3.1,
    tags: ["AI Tutoring", "Personalized Learning"],
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "c011",
    name: "QuantumLeap",
    website: "https://quantumleap.tech",
    sector: "AI / ML",
    stage: "Series A",
    country: "United States",
    city: "Boston",
    foundedYear: 2021,
    raisedAmount: 22000000,
    lastFundingDate: "2025-09-08",
    employeesEstimate: "51–100",
    score: 85,
    signalVelocity: 8.5,
    tags: ["Quantum Computing", "ML Optimization"],
    createdAt: "2025-07-05T00:00:00Z",
  },
  {
    id: "c012",
    name: "FleetPulse",
    website: "https://fleetpulse.move",
    sector: "Logistics",
    stage: "Seed",
    country: "Brazil",
    city: "São Paulo",
    foundedYear: 2023,
    raisedAmount: 5500000,
    lastFundingDate: "2025-08-25",
    employeesEstimate: "11–50",
    score: 72,
    signalVelocity: 6.3,
    tags: ["Fleet Management", "IoT", "Latin America"],
    createdAt: "2025-08-15T00:00:00Z",
  },
  {
    id: "c013",
    name: "LegalMind",
    website: "https://legalmind.ai",
    sector: "LegalTech",
    stage: "Series A",
    country: "United Kingdom",
    city: "London",
    foundedYear: 2022,
    raisedAmount: 9500000,
    lastFundingDate: "2025-07-22",
    employeesEstimate: "51–100",
    score: 76,
    signalVelocity: 6.1,
    tags: ["Contract Analysis", "AI Legal", "NLP"],
    createdAt: "2025-06-10T00:00:00Z",
  },
  {
    id: "c014",
    name: "NovaMaterials",
    website: "https://novamaterials.xyz",
    sector: "CleanTech",
    stage: "Series B+",
    country: "Japan",
    city: "Tokyo",
    foundedYear: 2018,
    raisedAmount: 52000000,
    lastFundingDate: "2025-04-15",
    employeesEstimate: "101–250",
    score: 90,
    signalVelocity: 9.0,
    tags: ["Advanced Materials", "Battery Tech"],
    createdAt: "2025-03-20T00:00:00Z",
  },
  {
    id: "c015",
    name: "PropelAI",
    website: "https://propelai.io",
    sector: "AI / ML",
    stage: "Seed",
    country: "France",
    city: "Paris",
    foundedYear: 2023,
    raisedAmount: 6200000,
    lastFundingDate: "2025-11-10",
    employeesEstimate: "11–50",
    score: 77,
    signalVelocity: 7.4,
    tags: ["Autonomous Agents", "Enterprise"],
    createdAt: "2025-10-05T00:00:00Z",
  },
  {
    id: "c016",
    name: "TerraCarbon",
    website: "https://terracarbon.eco",
    sector: "CleanTech",
    stage: "Series A",
    country: "Australia",
    city: "Sydney",
    foundedYear: 2021,
    raisedAmount: 11000000,
    lastFundingDate: "2025-06-15",
    employeesEstimate: "51–100",
    score: 81,
    signalVelocity: 7.8,
    tags: ["Carbon Credits", "Sustainability", "MRV"],
    createdAt: "2025-05-20T00:00:00Z",
  },
  {
    id: "c017",
    name: "MetaWear",
    website: "https://metawear.xyz",
    sector: "Consumer",
    stage: "Pre-Seed",
    country: "South Korea",
    city: "Seoul",
    foundedYear: 2024,
    raisedAmount: 950000,
    lastFundingDate: "2025-12-05",
    employeesEstimate: "1–10",
    score: 58,
    signalVelocity: 3.8,
    tags: ["AR/VR", "Wearables", "Fashion Tech"],
    createdAt: "2025-11-20T00:00:00Z",
  },
  {
    id: "c018",
    name: "DataNova",
    website: "https://datanova.ai",
    sector: "AI / ML",
    stage: "Series B+",
    country: "United States",
    city: "Seattle",
    foundedYear: 2019,
    raisedAmount: 78000000,
    lastFundingDate: "2025-03-20",
    employeesEstimate: "250+",
    score: 94,
    signalVelocity: 9.9,
    tags: ["Data Platform", "Enterprise AI", "Analytics"],
    createdAt: "2025-02-15T00:00:00Z",
  },
  {
    id: "c019",
    name: "InsureFlow",
    website: "https://insureflow.io",
    sector: "FinTech",
    stage: "Seed",
    country: "India",
    city: "Mumbai",
    foundedYear: 2023,
    raisedAmount: 3200000,
    lastFundingDate: "2025-10-18",
    employeesEstimate: "11–50",
    score: 66,
    signalVelocity: 5.0,
    tags: ["InsurTech", "Claims Automation"],
    createdAt: "2025-09-15T00:00:00Z",
  },
  {
    id: "c020",
    name: "RoboSurge",
    website: "https://robosurge.med",
    sector: "HealthTech",
    stage: "Series A",
    country: "Switzerland",
    city: "Zurich",
    foundedYear: 2020,
    raisedAmount: 25000000,
    lastFundingDate: "2025-05-30",
    employeesEstimate: "51–100",
    score: 84,
    signalVelocity: 8.3,
    tags: ["Surgical Robotics", "MedTech"],
    createdAt: "2025-04-25T00:00:00Z",
  },
  {
    id: "c021",
    name: "Gridwise",
    website: "https://gridwise.energy",
    sector: "CleanTech",
    stage: "Series A",
    country: "United States",
    city: "Denver",
    foundedYear: 2021,
    raisedAmount: 16000000,
    lastFundingDate: "2025-08-10",
    employeesEstimate: "51–100",
    score: 80,
    signalVelocity: 7.5,
    tags: ["Smart Grid", "Energy Management"],
    createdAt: "2025-07-10T00:00:00Z",
  },
  {
    id: "c022",
    name: "TalentGraph",
    website: "https://talentgraph.app",
    sector: "HR Tech",
    stage: "Pre-Seed",
    country: "Canada",
    city: "Vancouver",
    foundedYear: 2024,
    raisedAmount: 1100000,
    lastFundingDate: "2025-11-22",
    employeesEstimate: "1–10",
    score: 60,
    signalVelocity: 4.0,
    tags: ["Recruiting", "Skills Graph", "AI Matching"],
    createdAt: "2025-11-10T00:00:00Z",
  },
  {
    id: "c023",
    name: "CloudFort",
    website: "https://cloudfort.io",
    sector: "CyberSecurity",
    stage: "Series A",
    country: "United States",
    city: "Portland",
    foundedYear: 2022,
    raisedAmount: 13500000,
    lastFundingDate: "2025-09-15",
    employeesEstimate: "51–100",
    score: 78,
    signalVelocity: 6.7,
    tags: ["Cloud Security", "SASE", "Compliance"],
    createdAt: "2025-08-05T00:00:00Z",
  },
  {
    id: "c024",
    name: "UrbanBite",
    website: "https://urbanbite.food",
    sector: "FoodTech",
    stage: "Seed",
    country: "Netherlands",
    city: "Amsterdam",
    foundedYear: 2023,
    raisedAmount: 4800000,
    lastFundingDate: "2025-10-30",
    employeesEstimate: "11–50",
    score: 69,
    signalVelocity: 5.7,
    tags: ["Dark Kitchen", "Sustainable Food"],
    createdAt: "2025-10-01T00:00:00Z",
  },
];

// ─── Mock Signals (for future use in company profiles) ───
export const mockSignals: Signal[] = [
  {
    id: "s001",
    companyId: "c001",
    type: "Funding",
    title: "Series A — $18.5M",
    description: "Led by a16z Bio, with participation from existing seed investors.",
    date: "2025-11-15",
    createdAt: "2025-11-15T00:00:00Z",
  },
  {
    id: "s002",
    companyId: "c001",
    type: "Hiring",
    title: "Hiring 12 ML Engineers",
    description: "Posted 12 new ML engineer positions across SF and remote.",
    date: "2025-10-28",
    createdAt: "2025-10-28T00:00:00Z",
  },
  {
    id: "s003",
    companyId: "c001",
    type: "Product",
    title: "Launched SynthBio v2.0",
    description: "New AI-driven drug candidate screening module with 3x faster processing.",
    date: "2025-10-01",
    createdAt: "2025-10-01T00:00:00Z",
  },
  {
    id: "s004",
    companyId: "c003",
    type: "Funding",
    title: "Series B — $65M",
    description: "Largest round in LLM infrastructure space, led by Sequoia Capital.",
    date: "2025-07-10",
    createdAt: "2025-07-10T00:00:00Z",
  },
  {
    id: "s005",
    companyId: "c003",
    type: "Press",
    title: "Featured in TechCrunch",
    description: "Named one of the top 50 AI companies to watch in 2026.",
    date: "2025-12-01",
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "s006",
    companyId: "c009",
    type: "Patent",
    title: "Zero-Trust Architecture Patent",
    description: "Granted US patent for novel zero-trust network segmentation method.",
    date: "2025-04-20",
    createdAt: "2025-04-20T00:00:00Z",
  },
  {
    id: "s007",
    companyId: "c018",
    type: "Funding",
    title: "Series C — $78M",
    description: "Mega-round led by Tiger Global at $400M valuation.",
    date: "2025-03-20",
    createdAt: "2025-03-20T00:00:00Z",
  },
  {
    id: "s008",
    companyId: "c018",
    type: "Hiring",
    title: "Expanding to 300+ employees",
    description: "Opening new offices in London and Singapore.",
    date: "2025-06-15",
    createdAt: "2025-06-15T00:00:00Z",
  },
  {
    id: "s009",
    companyId: "c014",
    type: "Product",
    title: "Battery Tech Breakthrough",
    description: "Announced solid-state battery prototype with 2x energy density.",
    date: "2025-03-10",
    createdAt: "2025-03-10T00:00:00Z",
  },
  {
    id: "s010",
    companyId: "c011",
    type: "Press",
    title: "Forbes 30 Under 30",
    description: "Co-founders named to Forbes 30 Under 30 list in Enterprise Tech.",
    date: "2025-12-10",
    createdAt: "2025-12-10T00:00:00Z",
  },
];

// ─── Helper: Get unique values for filters ───
export function getUniqueSectors(): string[] {
  return [...new Set(mockCompanies.map((c) => c.sector))].sort();
}

export function getUniqueCountries(): string[] {
  return [...new Set(mockCompanies.map((c) => c.country))].sort();
}

export function getUniqueStages(): string[] {
  return [...new Set(mockCompanies.map((c) => c.stage))].sort();
}

// ─── Helper: Get latest signal for company ───
export function getLatestSignal(companyId: string): Signal | undefined {
  return mockSignals
    .filter((s) => s.companyId === companyId)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())[0];
}

// ─── Helper: Get signals for company ───
export function getCompanySignals(companyId: string): Signal[] {
  return mockSignals
    .filter((s) => s.companyId === companyId)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

// ─── Scoring Integration ───

/** Cache for scored companies to avoid recomputation */
let _scoredCompaniesCache: Company[] | null = null;

/**
 * Returns all companies with their `score` field replaced by the
 * dynamically computed score from the scoring engine.
 * Results are cached after first computation.
 */
export function getScoredCompanies(): Company[] {
  if (_scoredCompaniesCache) return _scoredCompaniesCache;

  _scoredCompaniesCache = mockCompanies.map((company) => {
    const signals = getCompanySignals(company.id);
    const breakdown = computeScoreBreakdown(company, signals);
    return { ...company, score: breakdown.total };
  });

  return _scoredCompaniesCache;
}

/**
 * Get the computed score for a single company.
 */
export function getComputedScore(companyId: string): number {
  const company = mockCompanies.find((c) => c.id === companyId);
  if (!company) return 0;
  const signals = getCompanySignals(companyId);
  return computeScoreBreakdown(company, signals).total;
}
